// src/screens/Home/Views/Mylist/ExternalImportModal.tsx
import { forwardRef, useCallback, useImperativeHandle, useMemo, useRef, useState } from 'react'
import { ScrollView, StyleSheet, TouchableOpacity, View } from 'react-native'
import Dialog, { type DialogType } from '@/components/common/Dialog'
import Input from '@/components/common/Input'
import Text from '@/components/common/Text'
import { LIST_IDS } from '@/config/constant'
import { useI18n } from '@/lang'
import type { Message } from '@/lang'
import listState from '@/store/list/state'
import { useTheme } from '@/store/theme/hook'
import { createStyle, toast } from '@/utils/tools'
import {
  ExternalImportError,
  getDefaultImportListName,
  importExternalPlaylist,
  type ExternalImportProgress,
  type ExternalImportSource,
  type ExternalImportTarget,
} from './importPlaylist'

export interface ExternalImportModalType {
  show: (currentListId: string) => void
}

const SOURCE_OPTIONS: Array<{ id: ExternalImportSource, name: string }> = [
  { id: 'tx', name: 'QQ音乐' },
  { id: 'wy', name: '网易云' },
  { id: 'kg', name: '酷狗' },
  { id: 'spotify', name: 'Spotify' },
]

const ERROR_MESSAGE_KEYS: Partial<Record<ExternalImportError['code'], keyof Message>> = {
  missing_token: 'playlist_import_modal__error_missing_token',
  invalid_link: 'playlist_import_modal__error_invalid_link',
  no_match: 'playlist_import_modal__error_no_match',
}

const PROGRESS_STAGE_KEYS: Record<ExternalImportProgress['stage'], keyof Message> = {
  fetch: 'playlist_import_modal__stage_fetch',
  match: 'playlist_import_modal__stage_match',
  save: 'playlist_import_modal__stage_save',
}

export default forwardRef<ExternalImportModalType>((props, ref) => {
  const dialogRef = useRef<DialogType>(null)
  const cancelRequestedRef = useRef(false)
  const theme = useTheme()
  const t = useI18n()
  const [source, setSource] = useState<ExternalImportSource>('tx')
  const [text, setText] = useState('')
  const [listName, setListName] = useState('')
  const [target, setTarget] = useState<ExternalImportTarget>('new')
  const [currentListId, setCurrentListId] = useState<string>(LIST_IDS.DEFAULT)
  const [neteaseToken, setNeteaseToken] = useState('')
  const [spotifyAccessToken, setSpotifyAccessToken] = useState('')
  const [spotifySavedTracks, setSpotifySavedTracks] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [statusText, setStatusText] = useState('')
  const [isError, setIsError] = useState(false)

  const reset = useCallback(() => {
    setSource('tx')
    setText('')
    setListName('')
    setTarget('new')
    setNeteaseToken('')
    setSpotifyAccessToken('')
    setSpotifySavedTracks(false)
    setStatusText('')
    setIsError(false)
    setIsLoading(false)
    cancelRequestedRef.current = false
  }, [])

  useImperativeHandle(ref, () => ({
    show(listId) {
      reset()
      setCurrentListId(listId)
      requestAnimationFrame(() => {
        dialogRef.current?.setVisible(true)
      })
    },
  }), [reset])

  const currentListName = useMemo(() => {
    switch (currentListId) {
      case LIST_IDS.DEFAULT:
        return t('list_name_default')
      case LIST_IDS.LOVE:
        return t('list_name_love')
      case LIST_IDS.TEMP:
        return t('list_name_temp')
      default:
        return listState.allList.find(list => list.id == currentListId)?.name ?? t('list_name_default')
    }
  }, [currentListId, t])

  const targetOptions = useMemo<Array<{ id: ExternalImportTarget, name: string }>>(() => [
    {
      id: 'new',
      name: t('playlist_import_modal__target_new'),
    },
    {
      id: 'current',
      name: t('playlist_import_modal__target_current', { name: currentListName }),
    },
    {
      id: 'love',
      name: t('list_name_love'),
    },
  ], [currentListName, t])

  const defaultListName = getDefaultImportListName(source, spotifySavedTracks)
  const isSpotify = source == 'spotify'
  const canSubmit = !isLoading && (
    isSpotify
      ? !!spotifyAccessToken.trim() && (spotifySavedTracks || !!text.trim())
      : !!text.trim()
  )

  const setProgress = useCallback((value: ExternalImportProgress) => {
    const stageText = t(PROGRESS_STAGE_KEYS[value.stage])
    setIsError(false)
    setStatusText(value.total
      ? `${stageText} ${value.current}/${value.total}`
      : stageText)
  }, [t])

  const handleSourceChange = (value: ExternalImportSource) => {
    if (value == source || isLoading) return
    setSource(value)
    setText('')
    setListName('')
    setSpotifySavedTracks(false)
    setStatusText('')
    setIsError(false)
  }

  const handleCancel = () => {
    if (isLoading) {
      cancelRequestedRef.current = true
      setIsError(false)
      setStatusText(t('playlist_import_modal__cancelling'))
      return
    }
    dialogRef.current?.setVisible(false)
  }

  const getErrorMessage = (error: unknown) => {
    if (error instanceof ExternalImportError) {
      const key = ERROR_MESSAGE_KEYS[error.code]
      if (key) return t(key)
    }
    return error instanceof Error ? error.message : String(error)
  }

  const handleSubmit = async() => {
    if (!canSubmit) return
    setIsLoading(true)
    setIsError(false)
    cancelRequestedRef.current = false
    setProgress({ stage: 'fetch', current: 0, total: 0 })

    try {
      const result = await importExternalPlaylist({
        source,
        text: text.trim(),
        listName: listName.trim(),
        target,
        currentListId,
        neteaseToken,
        spotifyAccessToken,
        spotifySavedTracks,
      }, setProgress, () => cancelRequestedRef.current)

      let message = t('playlist_import_modal__success', {
        total: result.total,
        imported: result.imported,
        unmatched: result.unmatched,
      })
      if (result.sourceTotal > result.total) {
        message += ` ${t('playlist_import_modal__success_partial', {
          sourceTotal: result.sourceTotal,
          total: result.total,
        })}`
      }
      toast(message)
      dialogRef.current?.setVisible(false)
    } catch (error) {
      if (error instanceof ExternalImportError && error.code == 'cancelled') {
        dialogRef.current?.setVisible(false)
      } else {
        setIsError(true)
        setStatusText(t('playlist_import_modal__failed', { message: getErrorMessage(error) }))
      }
    } finally {
      setIsLoading(false)
      cancelRequestedRef.current = false
    }
  }

  const fieldBorderColor = theme.isDark ? 'rgba(255,255,255,0.14)' : 'rgba(255,255,255,0.78)'

  return (
    <Dialog
      ref={dialogRef}
      title={t('playlist_import_modal__title')}
      height="78%"
      closeBtn={false}
      bgHide={false}
      keyHide={false}
      onHide={reset}
    >
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.content}
        keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.label} size={12} color={theme['q-text-secondary']}>
          {t('playlist_import_modal__source')}
        </Text>
        <View style={styles.sourceRow}>
          {SOURCE_OPTIONS.map(item => {
            const active = source == item.id
            return (
              <TouchableOpacity
                key={item.id}
                activeOpacity={0.7}
                disabled={isLoading}
                onPress={() => { handleSourceChange(item.id) }}
                style={[
                  styles.sourceButton,
                  {
                    backgroundColor: active ? theme['q-surface-tint'] : theme['q-surface-base'],
                    borderColor: active ? theme['c-primary-alpha-700'] : theme['q-outline'],
                  },
                ]}
              >
                <Text
                  size={12}
                  color={active ? theme['q-accent-text'] : theme['q-text-secondary']}
                  numberOfLines={1}
                >
                  {item.name}
                </Text>
              </TouchableOpacity>
            )
          })}
        </View>

        <Text style={styles.fieldLabel} size={12} color={theme['q-text-secondary']}>
          {isSpotify && spotifySavedTracks
            ? t('playlist_import_modal__spotify_liked')
            : t('playlist_import_modal__link')}
        </Text>
        <Input
          value={text}
          editable={!isLoading && !(isSpotify && spotifySavedTracks)}
          clearBtn
          onChangeText={setText}
          placeholder={isSpotify
            ? t('playlist_import_modal__spotify_link_placeholder')
            : t('playlist_import_modal__link_placeholder')}
        />

        {source == 'wy'
          ? <>
              <Text style={styles.fieldLabel} size={12} color={theme['q-text-secondary']}>
                {t('playlist_import_modal__netease_token')}
              </Text>
              <Input
                value={neteaseToken}
                editable={!isLoading}
                secureTextEntry
                clearBtn
                onChangeText={setNeteaseToken}
                placeholder={t('playlist_import_modal__netease_token_placeholder')}
              />
            </>
          : null}

        {isSpotify
          ? <>
              <Text style={styles.fieldLabel} size={12} color={theme['q-text-secondary']}>
                {t('playlist_import_modal__spotify_token')}
              </Text>
              <Input
                value={spotifyAccessToken}
                editable={!isLoading}
                secureTextEntry
                clearBtn
                onChangeText={setSpotifyAccessToken}
                placeholder={t('playlist_import_modal__spotify_token_placeholder')}
              />
              <TouchableOpacity
                activeOpacity={0.7}
                disabled={isLoading}
                onPress={() => { setSpotifySavedTracks(value => !value); setText('') }}
                style={[
                  styles.optionRow,
                  {
                    backgroundColor: spotifySavedTracks ? theme['q-surface-tint'] : theme['q-surface-base'],
                    borderColor: spotifySavedTracks ? theme['c-primary-alpha-700'] : fieldBorderColor,
                  },
                ]}
              >
                <View
                  style={[
                    styles.selectionMark,
                    {
                      borderColor: spotifySavedTracks ? theme['q-accent'] : theme['q-text-secondary'],
                      backgroundColor: spotifySavedTracks ? theme['q-accent'] : 'transparent',
                    },
                  ]}
                >
                  {spotifySavedTracks
                    ? <Text size={11} color={theme['q-surface-raised']}>✓</Text>
                    : null}
                </View>
                <Text size={13} color={theme['q-text-primary']}>
                  {t('playlist_import_modal__spotify_liked')}
                </Text>
              </TouchableOpacity>
            </>
          : null}

        <Text style={styles.fieldLabel} size={12} color={theme['q-text-secondary']}>
          {t('playlist_import_modal__target')}
        </Text>
        <View style={styles.targetList}>
          {targetOptions.map(item => {
            const active = target == item.id
            return (
              <TouchableOpacity
                key={item.id}
                activeOpacity={0.7}
                disabled={isLoading}
                onPress={() => { setTarget(item.id) }}
                style={[
                  styles.optionRow,
                  {
                    backgroundColor: active ? theme['q-surface-tint'] : theme['q-surface-base'],
                    borderColor: active ? theme['c-primary-alpha-700'] : fieldBorderColor,
                  },
                ]}
              >
                <View
                  style={[
                    styles.radioOuter,
                    { borderColor: active ? theme['q-accent'] : theme['q-text-secondary'] },
                  ]}
                >
                  {active
                    ? <View style={{ ...styles.radioInner, backgroundColor: theme['q-accent'] }} />
                    : null}
                </View>
                <Text size={13} color={theme['q-text-primary']} numberOfLines={1}>
                  {item.name}
                </Text>
              </TouchableOpacity>
            )
          })}
        </View>

        {target == 'new'
          ? <>
              <Text style={styles.fieldLabel} size={12} color={theme['q-text-secondary']}>
                {t('playlist_import_modal__list_name')}
              </Text>
              <Input
                value={listName}
                editable={!isLoading}
                clearBtn
                onChangeText={setListName}
                placeholder={defaultListName}
              />
            </>
          : null}

        {statusText
          ? <Text
              style={styles.status}
              size={12}
              color={isError ? '#c65b5b' : theme['q-text-secondary']}
            >
              {statusText}
            </Text>
          : null}
      </ScrollView>

      <View
        style={{
          ...styles.footer,
          borderTopColor: theme['q-outline'],
          backgroundColor: theme['q-surface-raised'],
        }}
      >
        <TouchableOpacity
          activeOpacity={0.7}
          onPress={handleCancel}
          style={[
            styles.footerButton,
            {
              backgroundColor: theme['q-surface-base'],
              borderColor: theme['q-outline'],
            },
          ]}
        >
          <Text size={13} color={theme['q-text-secondary']}>
            {t('cancel')}
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          activeOpacity={0.72}
          disabled={!canSubmit}
          onPress={() => { void handleSubmit() }}
          style={[
            styles.footerButton,
            styles.submitButton,
            {
              opacity: canSubmit ? 1 : 0.42,
              backgroundColor: theme['c-primary-alpha-700'],
              borderColor: theme['c-primary-alpha-700'],
            },
          ]}
        >
          <Text size={13} color={theme['q-accent-text']}>
            {isLoading
              ? t('playlist_import_modal__importing')
              : t('playlist_import_modal__submit')}
          </Text>
        </TouchableOpacity>
      </View>
    </Dialog>
  )
})

const styles = createStyle({
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 18,
  },
  label: {
    marginBottom: 8,
    fontWeight: '600',
  },
  fieldLabel: {
    marginTop: 16,
    marginBottom: 8,
    fontWeight: '600',
  },
  sourceRow: {
    flexDirection: 'row',
    gap: 7,
  },
  sourceButton: {
    flex: 1,
    height: 38,
    borderRadius: 11,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
  },
  targetList: {
    gap: 8,
  },
  optionRow: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
  },
  selectionMark: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  status: {
    marginTop: 14,
    lineHeight: 18,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  footerButton: {
    minWidth: 84,
    height: 40,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButton: {
    minWidth: 112,
  },
})

// src/renderer/views/List/MyList/components/ExternalImportModal.vue
<template>
  <material-modal :show="visible" bg-close teleport="#view" width="540px" max-width="calc(100% - 32px)" @close="handleClose">
    <div :class="$style.header">
      <h2>{{ $t('playlist_import_modal__title') }}</h2>
    </div>
    <main class="scroll" :class="$style.main">
      <section :class="$style.field">
        <h3 :class="$style.label">{{ $t('playlist_import_modal__source') }}</h3>
        <div :class="$style.sourceBtns">
          <button
            v-for="item in sourceOptions" :key="item.id" type="button"
            :class="[$style.sourceBtn, { [$style.active]: source == item.id }]"
            :disabled="isLoading"
            @click="source = item.id"
          >
            {{ item.name }}
          </button>
        </div>
      </section>

      <section :class="$style.field">
        <h3 :class="$style.label">{{ inputLabel }}</h3>
        <base-input
          v-model="text"
          :class="$style.input"
          :disabled="isLoading || (source == 'spotify' && spotifySavedTracks)"
          :placeholder="inputPlaceholder"
          :auto-paste="true"
        />
      </section>

      <section v-if="source == 'wy'" :class="$style.field">
        <h3 :class="$style.label">{{ $t('playlist_import_modal__netease_token') }}</h3>
        <base-input
          v-model="neteaseToken"
          :class="$style.input"
          :disabled="isLoading"
          type="password"
          :placeholder="$t('playlist_import_modal__netease_token_placeholder')"
        />
      </section>

      <section v-if="source == 'spotify'" :class="$style.field">
        <h3 :class="$style.label">{{ $t('playlist_import_modal__spotify_token') }}</h3>
        <base-input
          v-model="spotifyAccessToken"
          :class="$style.input"
          :disabled="isLoading"
          type="password"
          :placeholder="$t('playlist_import_modal__spotify_token_placeholder')"
        />
        <base-checkbox
          id="playlist_import_spotify_saved_tracks"
          v-model="spotifySavedTracks"
          :class="$style.checkbox"
          :disabled="isLoading"
          :label="$t('playlist_import_modal__spotify_liked')"
        />
      </section>

      <section :class="$style.field">
        <h3 :class="$style.label">{{ $t('playlist_import_modal__target') }}</h3>
        <div :class="$style.radioGroup">
          <base-checkbox
            v-for="item in targetOptions"
            :id="`playlist_import_target_${item.id}`"
            :key="item.id"
            v-model="target"
            need
            name="playlist_import_target"
            :value="item.id"
            :disabled="isLoading"
            :label="item.name"
          />
        </div>
      </section>

      <section v-if="target == 'new'" :class="$style.field">
        <h3 :class="$style.label">{{ $t('playlist_import_modal__list_name') }}</h3>
        <base-input
          v-model="listName"
          :class="$style.input"
          :disabled="isLoading"
          :placeholder="defaultListName"
        />
      </section>

      <div v-if="statusText" :class="$style.status">{{ statusText }}</div>
    </main>
    <footer :class="$style.footer">
      <base-btn outline :disabled="cancelRequested" @click="handleClose">{{ $t('btn_cancel') }}</base-btn>
      <base-btn :disabled="!canSubmit" @click="handleSubmit">{{ submitText }}</base-btn>
    </footer>
  </material-modal>
</template>

<script>
import { computed, ref, watch } from '@common/utils/vueTools'
import { useI18n } from '@renderer/plugins/i18n'
import { defaultList, loveList, userLists } from '@renderer/store/list/state'
import { dialog } from '@renderer/plugins/Dialog'
import { ExternalImportError, importExternalPlaylist } from '../importPlaylist'

const sourceOptions = [
  { id: 'tx', name: 'QQ音乐' },
  { id: 'wy', name: '网易云' },
  { id: 'kg', name: '酷狗' },
  { id: 'spotify', name: 'Spotify' },
]

const sourceNames = {
  tx: 'QQ音乐',
  wy: '网易云音乐',
  kg: '酷狗音乐',
  spotify: 'Spotify',
}

export default {
  props: {
    visible: {
      type: Boolean,
      default: false,
    },
    listId: {
      type: String,
      required: true,
    },
  },
  emits: ['update:visible'],
  setup(props, { emit }) {
    const t = useI18n()
    const source = ref('tx')
    const text = ref('')
    const listName = ref('')
    const target = ref('new')
    const neteaseToken = ref('')
    const spotifyAccessToken = ref('')
    const spotifySavedTracks = ref(false)
    const isLoading = ref(false)
    const cancelRequested = ref(false)
    const statusText = ref('')
    const progressStageKeys = {
      fetch: 'playlist_import_modal__stage_fetch',
      match: 'playlist_import_modal__stage_match',
      save: 'playlist_import_modal__stage_save',
    }
    const errorMessageKeys = {
      missing_token: 'playlist_import_modal__error_missing_token',
      invalid_link: 'playlist_import_modal__error_invalid_link',
      no_match: 'playlist_import_modal__error_no_match',
    }

    const currentListName = computed(() => {
      switch (props.listId) {
        case defaultList.id:
          return t(defaultList.name)
        case loveList.id:
          return t(loveList.name)
        default:
          return userLists.find(list => list.id == props.listId)?.name ?? t(defaultList.name)
      }
    })

    const targetOptions = computed(() => [
      {
        id: 'new',
        name: t('playlist_import_modal__target_new'),
      },
      {
        id: 'current',
        name: t('playlist_import_modal__target_current', { name: currentListName.value }),
      },
      {
        id: 'love',
        name: t(loveList.name),
      },
    ])

    const inputLabel = computed(() => {
      if (source.value == 'spotify' && spotifySavedTracks.value) return t('playlist_import_modal__spotify_liked')
      return t('playlist_import_modal__link')
    })

    const inputPlaceholder = computed(() => {
      if (source.value == 'spotify') return t('playlist_import_modal__spotify_link_placeholder')
      return t('playlist_import_modal__link_placeholder')
    })

    const defaultListName = computed(() => {
      if (source.value == 'spotify' && spotifySavedTracks.value) return 'Spotify 喜欢的歌曲'
      return `${sourceNames[source.value]}导入歌单`
    })

    const canSubmit = computed(() => {
      if (isLoading.value) return false
      if (source.value == 'spotify') {
        if (!spotifyAccessToken.value.trim()) return false
        return spotifySavedTracks.value || !!text.value.trim()
      }
      return !!text.value.trim()
    })

    const submitText = computed(() => isLoading.value ? t('playlist_import_modal__importing') : t('playlist_import_modal__submit'))

    const reset = () => {
      text.value = ''
      listName.value = ''
      neteaseToken.value = ''
      spotifyAccessToken.value = ''
      spotifySavedTracks.value = false
      statusText.value = ''
    }

    const setProgress = (value) => {
      const stageText = t(progressStageKeys[value.stage])
      statusText.value = value.total
        ? `${stageText} ${String(value.current)}/${String(value.total)}`
        : stageText
    }

    const handleClose = () => {
      if (isLoading.value) {
        // 导入中点击取消/关闭：请求中止当前导入，由导入流程在下一个检查点退出
        if (!cancelRequested.value) {
          cancelRequested.value = true
          statusText.value = t('playlist_import_modal__cancelling')
        }
        return
      }
      emit('update:visible', false)
    }

    const getErrorMessage = (error) => {
      if (error instanceof ExternalImportError && errorMessageKeys[error.code]) {
        return t(errorMessageKeys[error.code])
      }
      return error.message || String(error)
    }

    const handleSubmit = async() => {
      if (!canSubmit.value) return
      isLoading.value = true
      cancelRequested.value = false
      setProgress({
        stage: 'fetch',
        current: 0,
        total: 0,
      })

      try {
        const result = await importExternalPlaylist({
          source: source.value,
          text: text.value.trim(),
          listName: listName.value.trim() || defaultListName.value,
          target: target.value,
          currentListId: props.listId,
          neteaseToken: neteaseToken.value,
          spotifyAccessToken: spotifyAccessToken.value,
          spotifySavedTracks: spotifySavedTracks.value,
        }, value => {
          setProgress(value)
        }, () => cancelRequested.value)
        let message = t('playlist_import_modal__success', result)
        if (result.sourceTotal > result.total) message += ' ' + t('playlist_import_modal__success_partial', result)
        await dialog({
          teleport: '#view',
          message,
        })
        reset()
        emit('update:visible', false)
      } catch (error) {
        if (!(error instanceof ExternalImportError && error.code == 'cancelled')) {
          await dialog({
            teleport: '#view',
            message: t('playlist_import_modal__failed', { message: getErrorMessage(error) }),
          })
        }
      } finally {
        isLoading.value = false
        cancelRequested.value = false
        statusText.value = ''
      }
    }

    watch(source, () => {
      reset()
    })

    watch(spotifySavedTracks, (enabled) => {
      if (enabled) text.value = ''
    })

    return {
      sourceOptions,
      source,
      text,
      listName,
      target,
      neteaseToken,
      spotifyAccessToken,
      spotifySavedTracks,
      isLoading,
      cancelRequested,
      targetOptions,
      inputLabel,
      inputPlaceholder,
      defaultListName,
      canSubmit,
      submitText,
      statusText,
      handleClose,
      handleSubmit,
    }
  },
}
</script>

<style lang="less" module>
@import '@renderer/assets/styles/layout.less';

.header {
  flex: none;
  padding: 12px 18px 4px;
  text-align: center;

  h2 {
    font-size: 16px;
    line-height: 1.4;
  }
}

.main {
  flex: auto;
  width: 540px;
  max-width: calc(100vw - 32px);
  padding: 8px 18px 0;
  box-sizing: border-box;
}

.field {
  margin-bottom: 14px;
}

.label {
  margin-bottom: 7px;
  font-size: 12px;
  line-height: 1.4;
  color: var(--color-font-label);
}

.sourceBtns {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 8px;
}

.sourceBtn {
  min-width: 0;
  height: 32px;
  border: none;
  border-radius: @form-radius;
  background: rgba(255, 255, 255, .54);
  color: var(--color-button-font);
  box-shadow: inset 0 0 0 1px rgba(255, 255, 255, .62);
  cursor: pointer;
  transition: @transition-fast;
  transition-property: background-color, color, box-shadow, opacity;
  font-size: 13px;

  &:hover {
    color: var(--color-primary-dark-300);
    background-color: rgba(255, 255, 255, .72);
  }

  &:disabled {
    opacity: .5;
    cursor: default;
  }
}

.active {
  color: var(--color-primary);
  box-shadow: inset 0 0 0 1px var(--color-primary-alpha-800);
}

.input {
  width: 100%;
  box-sizing: border-box;
}

.checkbox {
  margin-top: 8px;
  font-size: 13px;
}

.radioGroup {
  display: flex;
  flex-flow: column nowrap;
  gap: 6px;
  font-size: 13px;
}

.status {
  padding: 8px 0 2px;
  font-size: 12px;
  line-height: 1.4;
  color: var(--color-font-label);
}

.footer {
  flex: none;
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding: 14px 18px 18px;
}
</style>
